#!/bin/bash

set -e
exec 3>&1
exec 1>&2


INPUT='/tmp/input'
cat > "$INPUT" <&0

REPO_DIR=$(jq -r '.source.repo_path // ""' < $INPUT)
REDIS_HOST=$(jq -r '.source.redis_host // ""' < $INPUT)
for v in REPO_DIR REDIS_HOST
do
if [[ -z "${!v}" ]]
   then
     echo "${!v} is not specified"
     exit 1
fi
done

# $1 - redis host $2 - key
get_redis() {
  result=$(redis-cli -h $1 get $2)
  if [ $? -eq 1 ]
  then
    echo "cant get value from redis"
    exit 1
  elif [ -z "$result" ]
  then
    echo "nothing found by key"
    exit 1
  fi
  DOCKER_TAG=$result
  export DOCKER_TAG
}

get_redis $REDIS_HOST $BUILD_TEAM_NAME:$BUILD_PIPELINE_NAME:$BUILD_ID
echo $DOCKER_TAG > /tmp/build/get/tag

echo "{\"version\":{\"ref\":\"$BUILD_TEAM_NAME:$BUILD_PIPELINE_NAME:$BUILD_ID\"}}" >&3
